// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2002
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.2.2

package chat;

//
// IDL:Chatter:1.0
//
final public class ChatterHolder implements org.omg.CORBA.portable.Streamable
{
    public Chatter value;

    public
    ChatterHolder()
    {
    }

    public
    ChatterHolder(Chatter initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = ChatterHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        ChatterHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return ChatterHelper.type();
    }
}
