// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2002
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.2.2

package chat;

//
// IDL:ChatService:1.0
//
final public class ChatServiceHolder implements org.omg.CORBA.portable.Streamable
{
    public ChatService value;

    public
    ChatServiceHolder()
    {
    }

    public
    ChatServiceHolder(ChatService initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = ChatServiceHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        ChatServiceHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return ChatServiceHelper.type();
    }
}
