// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2002
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.2.2

package chat;

//
// IDL:ChatService:1.0
//
/***/

public interface ChatService extends ChatServiceOperations,
                                     org.omg.CORBA.Object,
                                     org.omg.CORBA.portable.IDLEntity
{
}
